### ISSUE TITLE
Обновить линки 

### ISSUE THREAD

**Issue by SDesya74** [mineprogramming/innercore-docs#16]
На страницах документации у каждого метода есть ссылка, ведущая на место в файле, где декларация была прописана. Сейчас она ведёт на устаревший файл доков в репо тулчейна Жеки.

В gruntfile.js на 29 строке указан префик урла, на который надо сделать ссылку. Надо заменить его на адрес сгенерированного файла core-engine.d.ts

Возможно стоит использовать https://docs.mineprogramming.org/core-engine.d.ts

**Comment by DMHYT** [comment]
Я нигде не нашёл инфы по поводу того, как генерировать линки на строки по другому шаблону, а сейчас зашёл в репу этого плагина для тайпдока, а там исью 2017 года как раз с этой самой проблемой, которую разраб так и не решил. Так что тут либо форкать его пакет и переделывать его под нас, если это можно, либо при деплое пушить корэнжин на какой-то гит, и поставить в грантфайле нужную ссылку.

**Comment by SDesya74** [comment]
Я в первом комментарии как раз указал этот файл, он на сайте доков есть. Если нужен именно гит — можно использовать артефакты автосборки в GitHub Actions.

**Comment by SDesya74** [comment]
Привет от детей #mineprogramming | Public
